Repository AY2223S1-CS2103T-W13-3/tp, pull requests merged in 2022-11, with the labels that each got.

#296 Draft PPP: Rende
  docs/team/wr3nd3.md
Labels: type.PPP

#298 Update waynezsy PPP
  docs/team/waynezsy.md
Labels: type.PPP

#279 Reorder UG features and summary table
  docs/UserGuide.md
Labels: type.UG

#331 Update Rende PPP
  docs/team/wr3nd3.md
Labels: type.PPP

#324 Update DG for cleardebts and deletedebts
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ClearDebtsObjectDiagram.puml
  docs/diagrams/ClearDebtsObjectDiagramAfter.puml
  docs/diagrams/DeleteDebtAfterObjectDiagram.puml
  docs/diagrams/DeleteDebtObjectDiagram.puml
  docs/images/ClearDebtsObjectDiagram.png
  docs/images/ClearDebtsObjectDiagramAfter.png
  docs/images/DeleteDebtAfterObjectDiagram.png
  docs/images/DeleteDebtObjectDiagram.png
Labels: type.DG
