Repository AY2223S1-CS2103T-W13-3/tp, pull requests merged in 2022-10, with the labels that each got.

#71 Remove default debt from `DebtListBuilder`
  src/test/java/paymelah/testutil/DebtListBuilder.java
Labels: priority.Medium, type.Task

#136 Add MarkCommand and UnmarkCommand to DG
  docs/DeveloperGuide.md
Labels: type.DG

#154 Repurpose email field to telegram handle field
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/paymelah/logic/commands/AddCommand.java
  src/main/java/paymelah/logic/commands/AddDebtCommand.java
  src/main/java/paymelah/logic/commands/ClearDebtsCommand.java
  src/main/java/paymelah/logic/commands/DeleteDebtCommand.java
  src/main/java/paymelah/logic/commands/EditCommand.java
  src/main/java/paymelah/logic/commands/FindCommand.java
  src/main/java/paymelah/logic/commands/SplitDebtCommand.java
  src/main/java/paymelah/logic/parser/AddCommandParser.java
  src/main/java/paymelah/logic/parser/CliSyntax.java
  src/main/java/paymelah/logic/parser/EditCommandParser.java
  src/main/java/paymelah/logic/parser/FindCommandParser.java
  src/main/java/paymelah/logic/parser/ParserUtil.java
  src/main/java/paymelah/model/person/Address.java
  src/main/java/paymelah/model/person/Email.java
  src/main/java/paymelah/model/person/Person.java
  src/main/java/paymelah/model/person/PersonMatchesDescriptorPredicate.java
  src/main/java/paymelah/model/person/Telegram.java
  src/main/java/paymelah/model/util/SampleDataUtil.java
  src/main/java/paymelah/storage/JsonAdaptedPerson.java
  src/main/java/paymelah/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/paymelah/logic/LogicManagerTest.java
  src/test/java/paymelah/logic/commands/CommandTestUtil.java
  src/test/java/paymelah/logic/commands/PersonDescriptorTest.java
  src/test/java/paymelah/logic/parser/AddCommandParserTest.java
  src/test/java/paymelah/logic/parser/EditCommandParserTest.java
  src/test/java/paymelah/logic/parser/ParserUtilTest.java
  src/test/java/paymelah/model/person/EmailTest.java
  src/test/java/paymelah/model/person/PersonTest.java
  src/test/java/paymelah/model/person/TelegramHandleTest.java
  src/test/java/paymelah/storage/JsonAdaptedPersonTest.java
  src/test/java/paymelah/testutil/PersonBuilder.java
  src/test/java/paymelah/testutil/PersonDescriptorBuilder.java
  src/test/java/paymelah/testutil/PersonUtil.java
  src/test/java/paymelah/testutil/TypicalPersons.java
Labels: priority.High
